spring:
  application:
    name: gateway-mall
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.2:8848
    sentinel:
      sentinel:
        transport:
          port: 8005
          dashboard: localhost:8080
    gateway:
      routes:
        - id: order_route
          uri: lb://order-mall
          predicates:
            - Path=/order/**
        - id: product_route
          uri: lb://product-mall
          predicates:
            - Path=/sku/**

server:
  port: 8085
