server:
  port: 8086
spring:
  application:
    name: order-mall
  datasource:
    url: jdbc:mysql://localhost:3306/fshows_script?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fshows_user
    password: 2W#17Ht!Vt7J
mapper-locations: classpath:mapper/*.xml
