spring:
  application:
    name: product-mall
  redis:
    host: localhost         # Redis 服务器地址
    port: 6379              # Redis 端口
    password: yourpassword  # 如果有密码
    database: 0             # 使用的数据库索引
    timeout: 3000ms         # 连接超时时间
    lettuce:
      pool:
        max-active: 8       # 最大连接数
        max-idle: 8         # 最大空闲连接数
        min-idle: 0         # 最小空闲连接数
        max-wait: 5000ms    # 连接获取最大等待时间
server:
  port: 8083
